"""admins: email, es_dueno, permisos_json (gestor de administradores)

Revision ID: 037e2f2c8443
Revises: f498a2a5780f
Create Date: 2026-08-09 19:55:24.665146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '037e2f2c8443'
down_revision = 'f498a2a5780f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('es_dueno', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('permisos_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.create_unique_constraint('uq_admins_email', ['email'])

    # El/los admins que ya existían pasan a ser el "dueño" (acceso total +
    # gestión de usuarios). El más viejo (min id) queda como dueño.
    op.execute("UPDATE admins SET es_dueno = false WHERE es_dueno IS NULL")
    op.execute("UPDATE admins SET es_dueno = true WHERE id = (SELECT MIN(id) FROM admins)")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_constraint('uq_admins_email', type_='unique')
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('permisos_json')
        batch_op.drop_column('es_dueno')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
