"""add notas privadas a propiedades

Revision ID: 1a3f5a7bde4b
Revises: a1f4c8d92b07
Create Date: 2026-07-23 13:56:18.351176

Apuntes internos del agente sobre la propiedad. No confundir con
`descripcion`, que es el texto del aviso: esto no sale nunca al sitio
publico (ver Propiedad.as_dict_publico).
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a3f5a7bde4b'
down_revision = 'a1f4c8d92b07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('propiedades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notas', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('propiedades', schema=None) as batch_op:
        batch_op.drop_column('notas')

    # ### end Alembic commands ###
