"""add investigacion_json a captacion_leads

Revision ID: 20140c9b2828
Revises: 1a3f5a7bde4b
Create Date: 2026-07-29 13:57:55.760262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20140c9b2828'
down_revision = '1a3f5a7bde4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('captacion_leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('investigacion_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('captacion_leads', schema=None) as batch_op:
        batch_op.drop_column('investigacion_json')

    # ### end Alembic commands ###
