"""empty message

Revision ID: 288212811a77
Revises: 
Create Date: 2025-03-06 08:12:44.569025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288212811a77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('fotos', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('fotos')
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
