"""Actualizar base de datos

Revision ID: 9a773bf2b3d8
Revises: 
Create Date: 2025-02-24 12:00:49.647522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a773bf2b3d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nueva_tabla')
    with op.batch_alter_table('propiedades', schema=None) as batch_op:
        batch_op.drop_index('ix_propiedades_direccion')
        batch_op.drop_index('ix_propiedades_id')

    op.drop_table('propiedades')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index('ix_clientes_id')
        batch_op.drop_index('ix_clientes_nombre')

    op.drop_table('clientes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(), nullable=True),
    sa.Column('contacto', sa.VARCHAR(), nullable=True),
    sa.Column('tipo', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index('ix_clientes_nombre', ['nombre'], unique=False)
        batch_op.create_index('ix_clientes_id', ['id'], unique=False)

    op.create_table('propiedades',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('direccion', sa.VARCHAR(), nullable=True),
    sa.Column('precio', sa.FLOAT(), nullable=True),
    sa.Column('tipo', sa.VARCHAR(), nullable=True),
    sa.Column('estado', sa.VARCHAR(), nullable=True),
    sa.Column('descripcion', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('propiedades', schema=None) as batch_op:
        batch_op.create_index('ix_propiedades_id', ['id'], unique=False)
        batch_op.create_index('ix_propiedades_direccion', ['direccion'], unique=False)

    op.create_table('nueva_tabla',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
