"""add candidatos_json a captacion_leads

Revision ID: dcd41944ba17
Revises: 20140c9b2828
Create Date: 2026-07-29 14:30:30.119819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcd41944ba17'
down_revision = '20140c9b2828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('captacion_leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('candidatos_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('captacion_leads', schema=None) as batch_op:
        batch_op.drop_column('candidatos_json')

    # ### end Alembic commands ###
