"""add nombre_campo

Revision ID: e014c9f339fd
Revises: 3e98fca45bb7
Create Date: 2026-06-01 12:09:49.467753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e014c9f339fd'
down_revision = '3e98fca45bb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('propiedades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_campo', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('propiedades', schema=None) as batch_op:
        batch_op.drop_column('nombre_campo')

    # ### end Alembic commands ###
