"""admins: es_admin (nivel Administrador de acceso total)

Revision ID: e7ac4aca1821
Revises: 037e2f2c8443
Create Date: 2026-08-10 12:36:29.631561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7ac4aca1821'
down_revision = '037e2f2c8443'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_admin', sa.Boolean(), nullable=True))
    op.execute("UPDATE admins SET es_admin = false WHERE es_admin IS NULL")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('es_admin')

    # ### end Alembic commands ###
