"""add parcela_id (FK a parcelas_catastrales) a captacion_leads

Revision ID: f498a2a5780f
Revises: dcd41944ba17
Create Date: 2026-07-29 14:50:21.246738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f498a2a5780f'
down_revision = 'dcd41944ba17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('captacion_leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parcela_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_captacion_leads_parcela_id', 'parcelas_catastrales', ['parcela_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('captacion_leads', schema=None) as batch_op:
        batch_op.drop_constraint('fk_captacion_leads_parcela_id', type_='foreignkey')
        batch_op.drop_column('parcela_id')

    # ### end Alembic commands ###
